name: Terraform EC2 Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/main' && 'arn:aws:iam::<ACCOUNT_ID_M3L>:role/github-oidc-role-prod' || 'arn:aws:iam::<ACCOUNT_ID_1084>:role/github-oidc-role-dev' }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Select workspace based on branch
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [ "$BRANCH" = "main" ]; then ENV=prod; else ENV=dev; fi
          echo "ENVIRONMENT=$ENV" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init -backend-config=terraform/backend.${{ env.ENVIRONMENT }}.tfvars

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=terraform/envs/${{ env.ENVIRONMENT }}.tfvars -out=tfplan

      - name: Manual approval
        if: github.ref == 'refs/heads/main'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Approve production apply"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
