name: Terraform EC2 Deployment
if: false

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      env:
        description: "Environment to deploy"
        required: true
        default: dev
        type: choice
        options: [dev, uat, prod]

env:
  AWS_REGION: us-east-1
  ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.env || 'dev' }}

concurrency:
  group: deploy-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.env || 'dev' }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::108471662249:role/GhaDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Debug selected env
        run: echo "Selected ENV=${ENV}"

      - name: Terraform Init (remote backend)
        run: terraform init -backend-config=backend.${{ env.ENV }}.tfvars

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (${{ env.ENV }})
        run: terraform plan -var-file=envs/${{ env.ENV }}.tfvars -out=tfplan

      - name: Terraform Apply (${{ env.ENV }})
        if: ${{ github.event_name == 'workflow_dispatch' || env.ENV != 'prod' }}
        run: terraform apply -auto-approve tfplan

      - name: Publish EC2 link
        run: |
          IP=$(terraform output -json | jq -r '.public_ip.value')
          echo "## EC2 Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${ENV}" >> $GITHUB_STEP_SUMMARY
          echo "**Public IP:** $IP" >> $GITHUB_STEP_SUMMARY
          echo "[Open Website](http://$IP)" >> $GITHUB_STEP_SUMMARY
